### ISSUE TITLE
Can't compile "dev" and other problems.

### ISSUE THREAD

**Issue by tvaughan** [omcljs/om#369]
I'd like to play around with om.next and one of the first things I'm trying to do is compile the example in this repository. However, I can't. Any idea what I'm doing wrong?

    $ git ll | head -1
    e0cc322 (HEAD -> master, origin/master, origin/HEAD) bump dep
    $ lein cljsbuild once dev
    Compiling ClojureScript.
    Compiling "resources/out/app.js" from ["src" "dev"]...
    31mCompiling "resources/out/app.js" failed.0m
    clojure.lang.ExceptionInfo: failed compiling file:dev/om/dev.cljs {:file #object[java.io.File 0x5a1a20ae "dev/om/dev.cljs"]}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.compiler$compile_file$fn__2629.invoke(compiler.cljc:1344)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1306)
	at cljs.compiler$compile_root.invoke(compiler.cljc:1381)
	at cljs.closure$compile_dir.invoke(closure.clj:438)
	at cljs.closure$fn__2996.invoke(closure.clj:478)
	at cljs.closure$fn__2954$G__2949__2961.invoke(closure.clj:383)
	at cljs.closure$fn__3003.invoke(closure.clj:492)
	at cljs.closure$fn__2954$G__2949__2961.invoke(closure.clj:383)
	at cljsbuild.compiler.SourcePaths$fn__134.invoke(compiler.clj:67)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$mapcat.doInvoke(core.clj:2660)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at cljsbuild.compiler.SourcePaths._compile(compiler.clj:67)
	at cljs.closure$build.invoke(closure.clj:1674)
	at cljs.closure$build.invoke(closure.clj:1627)
	at cljsbuild.compiler$compile_cljs$fn__145.invoke(compiler.clj:81)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:80)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:180)
	at user$eval277$iter__313__317$fn__318$fn__336.invoke(form-init1636115337404745867.clj:1)
	at user$eval277$iter__313__317$fn__318.invoke(form-init1636115337404745867.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$dorun.invoke(core.clj:3009)
	at clojure.core$doall.invoke(core.clj:3025)
	at user$eval277.invoke(form-init1636115337404745867.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
    Caused by: clojure.lang.ExceptionInfo: nth not supported on this type: Symbol at line 16 dev/om/dev.cljs {:file "dev/om/dev.cljs", :line 16, :column 1, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:541)
	at cljs.analyzer$macroexpand_1.invoke(analyzer.cljc:2371)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2401)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2570)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2569)
	at cljs.analyzer$fn__1584.invoke(analyzer.cljc:1592)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:2377)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:2382)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2403)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2570)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2569)
	at cljs.analyzer$analyze_do_statements_STAR_$fn__1534.invoke(analyzer.cljc:1386)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at cljs.analyzer$analyze_do_statements_STAR_.invoke(analyzer.cljc:1386)
	at cljs.analyzer$analyze_do_statements.invoke(analyzer.cljc:1389)
	at cljs.analyzer$fn__1539.invoke(analyzer.cljc:1393)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:2377)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:2382)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2403)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2404)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2570)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2569)
	at cljs.analyzer$analyze_do_statements_STAR_$fn__1534.invoke(analyzer.cljc:1386)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at cljs.analyzer$analyze_do_statements_STAR_.invoke(analyzer.cljc:1386)
	at cljs.analyzer$analyze_do_statements.invoke(analyzer.cljc:1389)
	at cljs.analyzer$fn__1539.invoke(analyzer.cljc:1393)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:2377)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:2382)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2403)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2570)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2569)
	at cljs.analyzer$analyze_let_body_STAR_.invoke(analyzer.cljc:1472)
	at cljs.analyzer$analyze_let_body.invoke(analyzer.cljc:1477)
	at cljs.analyzer$analyze_let.invoke(analyzer.cljc:1493)
	at cljs.analyzer$fn__1555.invoke(analyzer.cljc:1505)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:2377)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:2382)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2403)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2404)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2404)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2570)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2569)
	at cljs.analyzer$analyze_do_statements_STAR_$fn__1534.invoke(analyzer.cljc:1386)
	at clojure.core$map$fn__4553.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at cljs.analyzer$analyze_do_statements_STAR_.invoke(analyzer.cljc:1386)
	at cljs.analyzer$analyze_do_statements.invoke(analyzer.cljc:1389)
	at cljs.analyzer$fn__1539.invoke(analyzer.cljc:1393)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:2377)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:2382)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2403)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:2404)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:2512)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2559)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2575)
	at cljs.compiler$compile_file_STAR_$fn__2588.invoke(compiler.cljc:1215)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1143)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1166)
	at cljs.compiler$compile_file$fn__2629.invoke(compiler.cljc:1327)
	... 45 more
    Caused by: java.lang.UnsupportedOperationException: nth not supported on this type: Symbol
	at clojure.lang.RT.nthFrom(RT.java:933)
	at clojure.lang.RT.nth(RT.java:883)
	at cljs.core$adapt_obj_params.invoke(core.clj:700)
	at cljs.core$add_obj_methods$fn__2967$fn__2969.invoke(core.clj:725)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1735)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invoke(core.clj:634)
	at cljs.analyzer$macroexpand_1_STAR_.invoke(analyzer.cljc:2331)
	... 147 more
    Subprocess failed

I've installed om locally via `lein install` so that I can use it in my own app. (I bumped the version number to be sure I'm really using my checkout of om.) I've created what I *think* is a valid om.next app.

    (ns (:require [om.next :as om :refer-macros [defui]]
                  [om.dom :as dom]))

    (defui HelloWorld
      static om/IQueryParams
      (params [this]
        {})
      static om/IQuery
      (query [this]
        '{})
      Object
      (render [this]
          (apply dom/div nil
            (dom/h2 nil "Hi."))))

This seems to compile. However I do see these warnings:

    WARNING: No such namespace: goog.object, could not locate goog/object.cljs, goog/object.cljc, or Closure namespace "" at line 6 src/mametipsum/core.cljs
    WARNING: No such namespace: goog.object, could not locate goog/object.cljs, goog/object.cljc, or Closure namespace "" at line 6 src/mametipsum/core.cljs

When I load my app in my browser (Safari) I see:

    [Error] TypeError: undefined is not an object (evaluating 'React.Component.prototype')
	(anonymous function) (core.cljs:6)

Where line 6 is `(defui HelloWorld` in the example above.

I don't know what is and what isn't related so I'm just including everything I've come across so far.

Finally, where can I find the example that was shown in https://www.youtube.com/watch?v=ByNs9TG30E8?

Thanks!

**Comment by tvaughan** [comment]
> When I load my app in my browser (Safari) I see:

OK. This is weird. Now I see:

    [Warning] Figwheel: Compile Warning - No such namespace: goog.object, could not locate goog/object.cljs, goog/object.cljc, or Closure namespace "" at line 5 src/mametipsum/core.cljs (utils.js, line 90, x2)
    [Warning] Figwheel: Not loading code with warnings -  /mametipsum/core.js (client.js, line 181)

**Comment by wilkerlucio** [comment]
Hi Tom

Try to require goog.object into your namespace, it's weird that we need to
do that, but here it does the trick:

(:require [goog.object])

**Comment by tvaughan** [comment]
Thanks @wilkerlucio. I didn't try that because I didn't see that done in any of the other examples I looked at. When I add that it does get rid of the warning, but I assume this just masks the real problem. Or no?

I should say I did run through https://github.com/omcljs/om/wiki/Basic-Tutorial earlier today without a hitch. It was only when I tried to switch to om.next that I started to have problems.

OK, I'm really confused now. I'm back to my earlier error.

    [Error] TypeError: undefined is not an object (evaluating 'React.Component.prototype')
    (anonymous function) (core.cljs:6)

Something's wonky, but what...

**Comment by wilkerlucio** [comment]
Tom, what I did be able to make it work here (kind of) was just to copy
most parts of the sources from this David Nolan project:
https://github.com/KitchenTableCoders/immutable-stack/blob/qcon/contacts/src/cljs/contacts/demo2.cljs

Try those and see if works for you.

**Comment by swannodette** [comment]
Please do not open issues about functionality under development. Thanks.
