### ISSUE TITLE
om-async tutorial lein figwheel crashes with clojure 1.7.0

### ISSUE THREAD

**Issue by metatron-the-chronicler** [omcljs/om#370]
Lein figwheel fails to execute correctly when using clojure 1.7 on a windows 7 machine.

lein cljsbuild prints the following error:

Reloading Clojure file "\om_async\core.clj" failed.
clojure.lang.Compiler$CompilerException: clojure.lang.ArityException: Wrong number of arg
 (2) passed to: StringReader, compiling:(abnf.clj:189:28)
       Compiler.java:3628 clojure.lang.Compiler$InvokeExpr.eval
       Compiler.java:3622 clojure.lang.Compiler$InvokeExpr.eval
        Compiler.java:439 clojure.lang.Compiler$DefExpr.eval
       Compiler.java:6787 clojure.lang.Compiler.eval
       Compiler.java:7227 clojure.lang.Compiler.load
              RT.java:371 clojure.lang.RT.loadResourceScript
              RT.java:362 clojure.lang.RT.loadResourceScript
              RT.java:446 clojure.lang.RT.load
              RT.java:412 clojure.lang.RT.load
            core.clj:5866 clojure.core/load[fn]
            core.clj:5865 clojure.core/load
          RestFn.java:408 clojure.lang.RestFn.invoke
            core.clj:5671 clojure.core/load-one
            core.clj:5711 clojure.core/load-lib[fn]
            core.clj:5710 clojure.core/load-lib
          RestFn.java:142 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5749 clojure.core/load-libs
          RestFn.java:137 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5832 clojure.core/require
          RestFn.java:805 clojure.lang.RestFn.invoke
               core.clj:1 instaparse.core/eval4529[fn]
               core.clj:1 instaparse.core/eval4529
       Compiler.java:6782 clojure.lang.Compiler.eval
       Compiler.java:6771 clojure.lang.Compiler.eval
       Compiler.java:7227 clojure.lang.Compiler.load
              RT.java:371 clojure.lang.RT.loadResourceScript
              RT.java:362 clojure.lang.RT.loadResourceScript
              RT.java:446 clojure.lang.RT.load
              RT.java:412 clojure.lang.RT.load
            core.clj:5866 clojure.core/load[fn]
            core.clj:5865 clojure.core/load
          RestFn.java:408 clojure.lang.RestFn.invoke
            core.clj:5671 clojure.core/load-one
            core.clj:5711 clojure.core/load-lib[fn]
            core.clj:5710 clojure.core/load-lib
          RestFn.java:142 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5749 clojure.core/load-libs
          RestFn.java:137 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5832 clojure.core/require
          RestFn.java:436 clojure.lang.RestFn.invoke
               core.clj:1 clout.core/eval4523[fn]
               core.clj:1 clout.core/eval4523
       Compiler.java:6782 clojure.lang.Compiler.eval
       Compiler.java:6771 clojure.lang.Compiler.eval
       Compiler.java:7227 clojure.lang.Compiler.load
              RT.java:371 clojure.lang.RT.loadResourceScript
              RT.java:362 clojure.lang.RT.loadResourceScript
              RT.java:446 clojure.lang.RT.load
              RT.java:412 clojure.lang.RT.load
            core.clj:5866 clojure.core/load[fn]
            core.clj:5865 clojure.core/load
          RestFn.java:408 clojure.lang.RestFn.invoke
            core.clj:5671 clojure.core/load-one
            core.clj:5711 clojure.core/load-lib[fn]
            core.clj:5710 clojure.core/load-lib
          RestFn.java:142 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5749 clojure.core/load-libs
          RestFn.java:137 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5832 clojure.core/require
          RestFn.java:482 clojure.lang.RestFn.invoke
               core.clj:1 compojure.core/eval4328[fn]
               core.clj:1 compojure.core/eval4328
       Compiler.java:6782 clojure.lang.Compiler.eval
       Compiler.java:6771 clojure.lang.Compiler.eval
       Compiler.java:7227 clojure.lang.Compiler.load
              RT.java:371 clojure.lang.RT.loadResourceScript
              RT.java:362 clojure.lang.RT.loadResourceScript
              RT.java:446 clojure.lang.RT.load
              RT.java:412 clojure.lang.RT.load
            core.clj:5866 clojure.core/load[fn]
            core.clj:5865 clojure.core/load
          RestFn.java:408 clojure.lang.RestFn.invoke
            core.clj:5671 clojure.core/load-one
            core.clj:5711 clojure.core/load-lib[fn]
            core.clj:5710 clojure.core/load-lib
          RestFn.java:142 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5749 clojure.core/load-libs
          RestFn.java:137 clojure.lang.RestFn.applyTo
             core.clj:632 clojure.core/apply
            core.clj:5832 clojure.core/require
          RestFn.java:551 clojure.lang.RestFn.invoke
     \om_async\core.clj:1 om-async.core/eval4130[fn]
     \om_async\core.clj:1 om-async.core/eval4130
       Compiler.java:6782 clojure.lang.Compiler.eval
       Compiler.java:6771 clojure.lang.Compiler.eval
       Compiler.java:7227 clojure.lang.Compiler.load
              RT.java:371 clojure.lang.RT.loadResourceScript
              RT.java:362 clojure.lang.RT.loadResourceScript
              RT.java:446 clojure.lang.RT.load
              RT.java:412 clojure.lang.RT.load
            core.clj:5866 clojure.core/load[fn]
            core.clj:5865 clojure.core/load
          RestFn.java:408 clojure.lang.RestFn.invoke
         compiler.clj:136 cljsbuild.compiler/reload-clojure[fn]
         compiler.clj:135 cljsbuild.compiler/reload-clojure
         compiler.clj:181 cljsbuild.compiler/run-compiler
form-init8337946453841846026.clj:1 user/eval4018[fn]
form-init8337946453841846026.clj:1 user/eval4018[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:507 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
            core.clj:3009 clojure.core/dorun
            core.clj:3025 clojure.core/doall
form-init8337946453841846026.clj:1 user/eval4018
       Compiler.java:6782 clojure.lang.Compiler.eval
       Compiler.java:6772 clojure.lang.Compiler.eval
       Compiler.java:7227 clojure.lang.Compiler.load
       Compiler.java:7165 clojure.lang.Compiler.loadFile
             main.clj:275 clojure.main/load-script
             main.clj:280 clojure.main/init-opt
             main.clj:308 clojure.main/initialize
             main.clj:343 clojure.main/null-opt
             main.clj:421 clojure.main/main
          RestFn.java:421 clojure.lang.RestFn.invoke
             Var.java:383 clojure.lang.Var.invoke
             AFn.java:156 clojure.lang.AFn.applyToHelper
             Var.java:700 clojure.lang.Var.applyTo
             main.java:37 clojure.main.main
Caused by: clojure.lang.ArityException: Wrong number of args (2) passed to: StringReader
             AFn.java:429 clojure.lang.AFn.throwArity
              AFn.java:36 clojure.lang.AFn.invoke
              cfg.clj:163 instaparse.cfg/eval5250[fn]
              cfg.clj:180 instaparse.cfg/process-string
              cfg.clj:217 instaparse.cfg/build-rule
            core.clj:2622 clojure.core/map[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:507 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
             core.clj:630 clojure.core/apply
              cfg.clj:215 instaparse.cfg/build-rule
            core.clj:2622 clojure.core/map[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:507 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
             core.clj:630 clojure.core/apply
              cfg.clj:211 instaparse.cfg/build-rule
              cfg.clj:214 instaparse.cfg/build-rule
            core.clj:2622 clojure.core/map[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:507 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
             core.clj:630 clojure.core/apply
              cfg.clj:215 instaparse.cfg/build-rule
            core.clj:2622 clojure.core/map[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:507 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
             core.clj:630 clojure.core/apply
              cfg.clj:211 instaparse.cfg/build-rule
              cfg.clj:207 instaparse.cfg/build-rule
            core.clj:2622 clojure.core/map[fn]
          LazySeq.java:40 clojure.lang.LazySeq.sval
          LazySeq.java:49 clojure.lang.LazySeq.seq
              RT.java:507 clojure.lang.RT.seq
             core.clj:137 clojure.core/seq
         protocols.clj:30 clojure.core.protocols/seq-reduce
        protocols.clj:101 clojure.core.protocols/fn
         protocols.clj:13 clojure.core.protocols/fn[fn]
            core.clj:6519 clojure.core/reduce
            core.clj:6600 clojure.core/into
              cfg.clj:277 instaparse.cfg/ebnf
             AFn.java:154 clojure.lang.AFn.applyToHelper
             AFn.java:144 clojure.lang.AFn.applyTo
       Compiler.java:3623 clojure.lang.Compiler$InvokeExpr.eval

Which looks simillar to this partial output from running lein figwheel (Note the arity exception.):

       at clojure.lang.RestFn.invoke(RestFn.java:408)
       at clojure.core$load_one.invoke(core.clj:5671)
       at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       at clojure.core$load_lib.doInvoke(core.clj:5710)
       at clojure.lang.RestFn.applyTo(RestFn.java:142)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$load_libs.doInvoke(core.clj:5749)
       at clojure.lang.RestFn.applyTo(RestFn.java:137)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$require.doInvoke(core.clj:5832)
       at clojure.lang.RestFn.invoke(RestFn.java:436)
       at clout.core$eval12869$loading__5340__auto____12870.invoke(core.clj:1)
       at clout.core$eval12869.invoke(core.clj:1)
       at clojure.lang.Compiler.eval(Compiler.java:6782)
       at clojure.lang.Compiler.eval(Compiler.java:6771)
       at clojure.lang.Compiler.load(Compiler.java:7227)
       at clojure.lang.RT.loadResourceScript(RT.java:371)
       at clojure.lang.RT.loadResourceScript(RT.java:362)
       at clojure.lang.RT.load(RT.java:446)
       at clojure.lang.RT.load(RT.java:412)
       at clojure.core$load$fn__5448.invoke(core.clj:5866)
       at clojure.core$load.doInvoke(core.clj:5865)
       at clojure.lang.RestFn.invoke(RestFn.java:408)
       at clojure.core$load_one.invoke(core.clj:5671)
       at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       at clojure.core$load_lib.doInvoke(core.clj:5710)
       at clojure.lang.RestFn.applyTo(RestFn.java:142)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$load_libs.doInvoke(core.clj:5749)
       at clojure.lang.RestFn.applyTo(RestFn.java:137)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$require.doInvoke(core.clj:5832)
       at clojure.lang.RestFn.invoke(RestFn.java:482)
       at compojure.core$eval12763$loading__5340__auto____12764.invoke(core.clj:1)
       at compojure.core$eval12763.invoke(core.clj:1)
       at clojure.lang.Compiler.eval(Compiler.java:6782)
       at clojure.lang.Compiler.eval(Compiler.java:6771)
       at clojure.lang.Compiler.load(Compiler.java:7227)
       at clojure.lang.RT.loadResourceScript(RT.java:371)
       at clojure.lang.RT.loadResourceScript(RT.java:362)
       at clojure.lang.RT.load(RT.java:446)
       at clojure.lang.RT.load(RT.java:412)
       at clojure.core$load$fn__5448.invoke(core.clj:5866)
       at clojure.core$load.doInvoke(core.clj:5865)
       at clojure.lang.RestFn.invoke(RestFn.java:408)
       at clojure.core$load_one.invoke(core.clj:5671)
       at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       at clojure.core$load_lib.doInvoke(core.clj:5710)
       at clojure.lang.RestFn.applyTo(RestFn.java:142)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$load_libs.doInvoke(core.clj:5749)
       at clojure.lang.RestFn.applyTo(RestFn.java:137)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$require.doInvoke(core.clj:5832)
       at clojure.lang.RestFn.invoke(RestFn.java:457)
       at compojure.route$eval12570$loading__5340__auto____12571.invoke(route.clj:1)
       at compojure.route$eval12570.invoke(route.clj:1)
       at clojure.lang.Compiler.eval(Compiler.java:6782)
       at clojure.lang.Compiler.eval(Compiler.java:6771)
       at clojure.lang.Compiler.load(Compiler.java:7227)
       at clojure.lang.RT.loadResourceScript(RT.java:371)
       at clojure.lang.RT.loadResourceScript(RT.java:362)
       at clojure.lang.RT.load(RT.java:446)
       at clojure.lang.RT.load(RT.java:412)
       at clojure.core$load$fn__5448.invoke(core.clj:5866)
       at clojure.core$load.doInvoke(core.clj:5865)
       at clojure.lang.RestFn.invoke(RestFn.java:408)
       at clojure.core$load_one.invoke(core.clj:5671)
       at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       at clojure.core$load_lib.doInvoke(core.clj:5710)
       at clojure.lang.RestFn.applyTo(RestFn.java:142)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$load_libs.doInvoke(core.clj:5749)
       at clojure.lang.RestFn.applyTo(RestFn.java:137)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$require.doInvoke(core.clj:5832)
       at clojure.lang.RestFn.invoke(RestFn.java:3659)
       at figwheel_sidecar.core$eval12564$loading__5340__auto____12565.invoke(core.c

       at figwheel_sidecar.core$eval12564.invoke(core.clj:1)
       at clojure.lang.Compiler.eval(Compiler.java:6782)
       at clojure.lang.Compiler.eval(Compiler.java:6771)
       at clojure.lang.Compiler.load(Compiler.java:7227)
       at clojure.lang.RT.loadResourceScript(RT.java:371)
       at clojure.lang.RT.loadResourceScript(RT.java:362)
       at clojure.lang.RT.load(RT.java:446)
       at clojure.lang.RT.load(RT.java:412)
       at clojure.core$load$fn__5448.invoke(core.clj:5866)
       at clojure.core$load.doInvoke(core.clj:5865)
       at clojure.lang.RestFn.invoke(RestFn.java:408)
       at clojure.core$load_one.invoke(core.clj:5671)
       at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       at clojure.core$load_lib.doInvoke(core.clj:5710)
       at clojure.lang.RestFn.applyTo(RestFn.java:142)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$load_libs.doInvoke(core.clj:5749)
       at clojure.lang.RestFn.applyTo(RestFn.java:137)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$require.doInvoke(core.clj:5832)
       at clojure.lang.RestFn.invoke(RestFn.java:3204)
       at figwheel_sidecar.repl$eval65$loading__5340__auto____66.invoke(repl.clj:1)
       at figwheel_sidecar.repl$eval65.invoke(repl.clj:1)
       at clojure.lang.Compiler.eval(Compiler.java:6782)
       at clojure.lang.Compiler.eval(Compiler.java:6771)
       at clojure.lang.Compiler.load(Compiler.java:7227)
       at clojure.lang.RT.loadResourceScript(RT.java:371)
       at clojure.lang.RT.loadResourceScript(RT.java:362)
       at clojure.lang.RT.load(RT.java:446)
       at clojure.lang.RT.load(RT.java:412)
       at clojure.core$load$fn__5448.invoke(core.clj:5866)
       at clojure.core$load.doInvoke(core.clj:5865)
       at clojure.lang.RestFn.invoke(RestFn.java:408)
       at clojure.core$load_one.invoke(core.clj:5671)
       at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       at clojure.core$load_lib.doInvoke(core.clj:5710)
       at clojure.lang.RestFn.applyTo(RestFn.java:142)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$load_libs.doInvoke(core.clj:5749)
       at clojure.lang.RestFn.applyTo(RestFn.java:137)
       at clojure.core$apply.invoke(core.clj:632)
       at clojure.core$require.doInvoke(core.clj:5832)
       at clojure.lang.RestFn.invoke(RestFn.java:436)
       at user$eval5.invoke(form-init7161389875402854319.clj:1)
       at clojure.lang.Compiler.eval(Compiler.java:6782)
       at clojure.lang.Compiler.eval(Compiler.java:6771)
       at clojure.lang.Compiler.load(Compiler.java:7227)
       at clojure.lang.Compiler.loadFile(Compiler.java:7165)
       at clojure.main$load_script.invoke(main.clj:275)
       at clojure.main$init_opt.invoke(main.clj:280)
       at clojure.main$initialize.invoke(main.clj:308)
       at clojure.main$null_opt.invoke(main.clj:343)
       at clojure.main$main.doInvoke(main.clj:421)
       at clojure.lang.RestFn.invoke(RestFn.java:421)
       at clojure.lang.Var.invoke(Var.java:383)
       at clojure.lang.AFn.applyToHelper(AFn.java:156)
       at clojure.lang.Var.applyTo(Var.java:700)
       at clojure.main.main(main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (2) passed to: StringReader
       at clojure.lang.AFn.throwArity(AFn.java:429)
       at clojure.lang.AFn.invoke(AFn.java:36)
       at instaparse.cfg$eval13596$safe_read_string__13597.invoke(cfg.clj:163)
       at instaparse.cfg$process_string.invoke(cfg.clj:180)
       at instaparse.cfg$build_rule.invoke(cfg.clj:217)
       at clojure.core$map$fn__4553.invoke(core.clj:2622)
       at clojure.lang.LazySeq.sval(LazySeq.java:40)
       at clojure.lang.LazySeq.seq(LazySeq.java:49)
       at clojure.lang.RT.seq(RT.java:507)
       at clojure.core$seq__4128.invoke(core.clj:137)
       at clojure.core$apply.invoke(core.clj:630)
       at instaparse.cfg$build_rule.invoke(cfg.clj:215)
       at clojure.core$map$fn__4553.invoke(core.clj:2622)
       at clojure.lang.LazySeq.sval(LazySeq.java:40)
       at clojure.lang.LazySeq.seq(LazySeq.java:49)
       at clojure.lang.RT.seq(RT.java:507)
       at clojure.core$seq__4128.invoke(core.clj:137)
       at clojure.core$apply.invoke(core.clj:630)
       at instaparse.cfg$build_rule.invoke(cfg.clj:211)
       at instaparse.cfg$build_rule.invoke(cfg.clj:214)
       at clojure.core$map$fn__4553.invoke(core.clj:2622)
       at clojure.lang.LazySeq.sval(LazySeq.java:40)
       at clojure.lang.LazySeq.seq(LazySeq.java:49)
       at clojure.lang.RT.seq(RT.java:507)
       at clojure.core$seq__4128.invoke(core.clj:137)
       at clojure.core$apply.invoke(core.clj:630)
       at instaparse.cfg$build_rule.invoke(cfg.clj:215)
       at clojure.core$map$fn__4553.invoke(core.clj:2622)
       at clojure.lang.LazySeq.sval(LazySeq.java:40)
       at clojure.lang.LazySeq.seq(LazySeq.java:49)
       at clojure.lang.RT.seq(RT.java:507)
       at clojure.core$seq__4128.invoke(core.clj:137)
       at clojure.core$apply.invoke(core.clj:630)
       at instaparse.cfg$build_rule.invoke(cfg.clj:211)
       at instaparse.cfg$build_rule.invoke(cfg.clj:207)
       at clojure.core$map$fn__4553.invoke(core.clj:2622)
       at clojure.lang.LazySeq.sval(LazySeq.java:40)
       at clojure.lang.LazySeq.seq(LazySeq.java:49)
       at clojure.lang.RT.seq(RT.java:507)
       at clojure.core$seq__4128.invoke(core.clj:137)
       at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
       at clojure.core.protocols$fn__6506.invoke(protocols.clj:101)
       at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
       at clojure.core$reduce.invoke(core.clj:6519)
       at clojure.core$into.invoke(core.clj:6600)
       at instaparse.cfg$ebnf.invoke(cfg.clj:277)
       at clojure.lang.AFn.applyToHelper(AFn.java:154)
       at clojure.lang.AFn.applyTo(AFn.java:144)
       at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
       ... 168 more
subprocess failed

**Comment by martinklepsch** [comment]
This is caused by older versions of instaparse I believe (compojure depends on instaparse).
Try explicitly pinning instaparse or updating compojure.
The mailing list is probably a better place to ask these kind of questions :)

Hope this helps.
