### ISSUE TITLE
getting could not locate cljsjs/react.cljs

### ISSUE THREAD

**Issue by jdkealy** [omcljs/om#472]
Getting "could not locate cljsjs/react.cljs" when following the quick start guide after running 

     lein run -m clojure.main script/figwheel.clj

I don't see any references to react at all in the core file, so I'm confused : 

    (ns om-tutorial.core
      (:require [goog.dom :as gdom]
                [om.next :as om :refer-macros [defui]]
                [om.dom :as dom]))
    
    (enable-console-print!)
    
    (println "Hello world!")
    

Stack trace : 
    Johns-MacBook-Pro:om-tutorial johnkealy$ lein run -m clojure.main script/figwheel.clj
    Figwheel: Starting server at http://localhost:3449
    Analyzing jar:file:/Users/johnkealy/.m2/repository/org/clojure/clojurescript/1.7.170/clojurescript-1.7.170.jar!/cljs/core.cljs
    Focusing on build ids: dev
    Compiling "resources/public/js/main.js" from ["src"]...
    Compiling "resources/public/js/main.js" failed.
    java.lang.AbstractMethodError: Method clojurescript_build/core/CompilableSourcePaths._find_sources(Ljava/lang/Object;)Ljava/lang/Object; is abstract
     at clojurescript_build.core.CompilableSourcePaths._find_sources (core.clj:-1)
    
    Analyzing src/om_tutorial/core.cljs
    Analyzing jar:file:/Users/johnkealy/.m2/repository/org/omcljs/om/1.0.0-alpha20/om-1.0.0-alpha20.jar!/om/dom.cljs
    Exception in thread "main" clojure.lang.ExceptionInfo: No such namespace: cljsjs.react, could not locate cljsjs/react.cljs, cljsjs/react.cljc, or Closure namespace "cljsjs.react" {:tag :cljs/analysis-error}, compiling:(/Users/johnkealy/srv/om-tutorial/script/figwheel.clj:17:1)
    	at clojure.lang.Compiler.load(Compiler.java:7239)
    	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    	at clojure.main$load_script.invoke(main.clj:275)
    	at clojure.main$script_opt.invoke(main.clj:337)
    	at clojure.main$main.doInvoke(main.clj:421)
    	at clojure.lang.RestFn.invoke(RestFn.java:408)
    	at clojure.lang.Var.invoke(Var.java:379)
    	at clojure.lang.AFn.applyToHelper(AFn.java:154)
    	at clojure.lang.Var.applyTo(Var.java:700)
    	at clojure.main.main(main.java:37)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:497)
    	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
    	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
    	at user$eval5.invoke(form-init608596793943736392.clj:1)
    	at clojure.lang.Compiler.eval(Compiler.java:6782)
    	at clojure.lang.Compiler.eval(Compiler.java:6772)
    	at clojure.lang.Compiler.load(Compiler.java:7227)
    	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    	at clojure.main$load_script.invoke(main.clj:275)
    	at clojure.main$init_opt.invoke(main.clj:280)
    	at clojure.main$initialize.invoke(main.clj:308)
    	at clojure.main$null_opt.invoke(main.clj:343)
    	at clojure.main$main.doInvoke(main.clj:421)
    	at clojure.lang.RestFn.invoke(RestFn.java:421)
    	at clojure.lang.Var.invoke(Var.java:383)
    	at clojure.lang.AFn.applyToHelper(AFn.java:156)
    	at clojure.lang.Var.applyTo(Var.java:700)
    	at clojure.main.main(main.java:37)
    Caused by: clojure.lang.ExceptionInfo: No such namespace: cljsjs.react, could not locate cljsjs/react.cljs, cljsjs/react.cljc, or Closure namespace "cljsjs.react" {:tag :cljs/analysis-error}
    	at clojure.core$ex_info.invoke(core.clj:4593)
    	at cljs.analyzer$error.invoke(analyzer.cljc:568)
    	at cljs.analyzer$error.invoke(analyzer.cljc:566)
    	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1656)
    	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2492)
    	at cljs.analyzer$analyze_STAR_$fn__2104.invoke(analyzer.cljc:2573)
    	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
    	at clojure.core$reduce.invoke(core.clj:6518)
    	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2573)
    	at cljs.analyzer$analyze.invoke(analyzer.cljc:2588)
    	at cljs.analyzer$analyze_file$fn__2155.invoke(analyzer.cljc:2838)
    	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:2833)
    	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1654)
    	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2492)
    	at cljs.analyzer$analyze_STAR_$fn__2104.invoke(analyzer.cljc:2573)
    	at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
    	at clojure.core$reduce.invoke(core.clj:6518)
    	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2573)
    	at cljs.analyzer$analyze.invoke(analyzer.cljc:2588)
    	at cljs.analyzer$analyze_file$fn__2155.invoke(analyzer.cljc:2838)
    	at cljs.analyzer$analyze_file.invoke(analyzer.cljc:2833)
    	at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:242)
    	at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:247)
    	at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:295)
    	at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:366)
    	at figwheel_sidecar.repl$start_repl.invoke(repl.clj:466)
    	at figwheel_sidecar.repl$cljs_repl.invoke(repl.clj:488)
    	at figwheel_sidecar.repl$cljs_repl.invoke(repl.clj:475)
    	at figwheel_sidecar.repl_api$cljs_repl.invoke(repl_api.clj:77)
    	at user$eval16211.invoke(figwheel.clj:17)
    	at clojure.lang.Compiler.eval(Compiler.java:6782)
    	at clojure.lang.Compiler.load(Compiler.java:7227)
    	... 36 more

**Comment by yusefnapora** [comment]
Just hit this as well.  Try changing `script/figwheel.clj` to the following:

```clojure
(require '[figwheel-sidecar.repl :as r]
         '[figwheel-sidecar.repl-api :as ra]
         '[cljs.closure :as cljsc])

(let [ups-deps (cljsc/get-upstream-deps)]
  (ra/start-figwheel!
    {:figwheel-options {}
     :build-ids ["dev"]
     :all-builds
     [{:id "dev"
       :figwheel true
       :source-paths ["src"]
       :compiler {:main 'om-tutorial.core
                  :asset-path "js"
                  :output-to "resources/public/js/main.js"
                  :output-dir "resources/public/js"
                  :ups-libs (:libs ups-deps)
                  :ups-foreign-libs (:foreign-libs ups-deps)
                  :verbose true}}]}))

(ra/cljs-repl)
```

I'm not familiar enough with the cljs compiler to know exactly why the above works, but it seems that React is included as a dependency of om, and it's not being pulled into the figwheel compiler environment.

The fix above is based on [this commit](https://github.com/cemerick/piggieback/commit/966c811ab817df0e818404943c473081337b286e) to piggieback, which I found via [this figwheel issue](https://github.com/bhauman/lein-figwheel/issues/109)

BTW, I'm now getting a different error (about not being able to find `cognitect.transit`).  But hey, it's progress :)

**Comment by yusefnapora** [comment]
It turns out that the changes to `script/fighweel.clj` above are unnecessary after updating figwheel.  So you should be fine if you just update your `project.clj`

**Comment by swannodette** [comment]
Please do not ask questions via issues. Find someone on #om Slack or #clojurescript IRC. Thanks.
